First draft of raml file
singularities/circular-works pull request #2
Opened 2016-11-05 13:42 UTC by atd

2016-11-10 16:36 UTC, nogates requested changes
I am missing the two updates endpoints, one for updating turns and one for updating groups

2016-11-10 16:47 UTC, nogates commented on api.raml
> +          }
what about using JSON api format http://jsonapi.org/ / https://github.com/rails-api/active_model_serializers

2016-11-10 19:29 UTC, atd commented on api.raml
> +          }
Done! Shall I include them in the request body also?

2016-11-10 19:32 UTC, atd commented on api.raml
> +          }
I seems so http://jsonapi.org/format/#crud-creating

2016-11-10 19:35 UTC, atd commented on api.raml
> +          }
I still need to define `type` and `attributes`

2016-11-10 23:09 UTC, nogates commented on api.raml
> +          }
Yep, the type is also mandatory

2016-11-11 17:08 UTC, atd commented
Please take a look at it now!

I rebased it on top of current master

2016-11-11 18:39 UTC, nogates approved these changes
awesome!

2016-11-12 12:27 UTC, merged